### ISSUE TITLE
how to createInvoice() ?

### ISSUE THREAD

**Issue by ghost** [Phobetor/billomat#2]
Hi,

this is how I try to create an invoice:

$billomat = $this->get('phobetor_billomat')->getClient();
$client = $billomat->getClients(array('number' => 10));
$clientId = $client['clients']['client'][0]['id'];
 $invoice = $billomat->createInvoice(array('client_id' => $clientId));

but I get the following exception:

Validation errors: [invoice] is a required object: Invoice
[invoice][client_id] is a required integer: ID of the client

What am I doing wrong?

Kind regards,
Dennis

**Comment by ghost** [comment]
done.

**Comment by Phobetor** [comment]
Hello @dennito,

thank you for your question. I see that the parameter structure is an issue and will add more examples for the different method types to the readme file.

Best regards
